package nl.ordina.graph

import com.databricks.spark.csv._
import org.apache.spark.sql.SQLContext
import org.scalatest.{FlatSpec, Matchers}

class MavenEntrySpec extends FlatSpec with Matchers {
  private val sqlContext = new SQLContext(SparkContextHolder.sc)

  "Reading a Base64 encoded JSON string of MavenEntries" should "result in a non-empty list of MavenEntries" in {
    val base64EncodedJson = "W3sidmVyc2lvbiI6ICIxLjAiLCAiZ3JvdXBpZCI6ICJlaGNhY2hlIiwgImFydGlmYWN0aWQiOiAiZWhjYWNoZSJ9LCB7InZlcnNpb24iOiAiMS4wIiwgImdyb3VwaWQiOiAiYW9wYWxsaWFuY2UiLCAiYXJ0aWZhY3RpZCI6ICJhb3BhbGxpYW5jZSJ9LCB7InZlcnNpb24iOiAiMS4yIiwgImdyb3VwaWQiOiAiY29tbW9ucy1jb2RlYyIsICJhcnRpZmFjdGlkIjogImNvbW1vbnMtY29kZWMifSwgeyJ2ZXJzaW9uIjogIjMuMSIsICJncm91cGlkIjogImNvbW1vbnMtY29sbGVjdGlvbnMiLCAiYXJ0aWZhY3RpZCI6ICJjb21tb25zLWNvbGxlY3Rpb25zIn0sIHsidmVyc2lvbiI6ICIxLjAuNCIsICJncm91cGlkIjogImNvbW1vbnMtbG9nZ2luZyIsICJhcnRpZmFjdGlkIjogImNvbW1vbnMtbG9nZ2luZyJ9LCB7InZlcnNpb24iOiAiMS4wLjIiLCAiZ3JvdXBpZCI6ICJqc3RsIiwgImFydGlmYWN0aWQiOiAianN0bCJ9LCB7InZlcnNpb24iOiAiMi4zIiwgImdyb3VwaWQiOiAic2VydmxldGFwaSIsICJhcnRpZmFjdGlkIjogInNlcnZsZXRhcGkifSwgeyJ2ZXJzaW9uIjogIjIuMC43IiwgImdyb3VwaWQiOiAib3JvIiwgImFydGlmYWN0aWQiOiAib3JvIn0sIHsidmVyc2lvbiI6ICIxLjcuMy4wIiwgImdyb3VwaWQiOiAiaHNxbGRiIiwgImFydGlmYWN0aWQiOiAiaHNxbGRiIn0sIHsidmVyc2lvbiI6ICIxLjIuOCIsICJncm91cGlkIjogImxvZzRqIiwgImFydGlmYWN0aWQiOiAibG9nNGoifSwgeyJ2ZXJzaW9uIjogIjMuOC4xIiwgImdyb3VwaWQiOiAianVuaXQiLCAiYXJ0aWZhY3RpZCI6ICJqdW5pdCJ9LCB7InZlcnNpb24iOiAiMS4xLjMiLCAiZ3JvdXBpZCI6ICJzcHJpbmdmcmFtZXdvcmsiLCAiYXJ0aWZhY3RpZCI6ICJzcHJpbmctY29yZSJ9LCB7InZlcnNpb24iOiAiMS4xLjMiLCAiZ3JvdXBpZCI6ICJzcHJpbmdmcmFtZXdvcmsiLCAiYXJ0aWZhY3RpZCI6ICJzcHJpbmctZGFvIn0sIHsidmVyc2lvbiI6ICIxLjEuMyIsICJncm91cGlkIjogInNwcmluZ2ZyYW1ld29yayIsICJhcnRpZmFjdGlkIjogInNwcmluZy1vcm0ifSwgeyJ2ZXJzaW9uIjogIjEuMS4zIiwgImdyb3VwaWQiOiAic3ByaW5nZnJhbWV3b3JrIiwgImFydGlmYWN0aWQiOiAic3ByaW5nLWNvbnRleHQifSwgeyJ2ZXJzaW9uIjogIjEuMS4zIiwgImdyb3VwaWQiOiAic3ByaW5nZnJhbWV3b3JrIiwgImFydGlmYWN0aWQiOiAic3ByaW5nLWFvcCJ9LCB7InZlcnNpb24iOiAiMS4xLjMiLCAiZ3JvdXBpZCI6ICJzcHJpbmdmcmFtZXdvcmsiLCAiYXJ0aWZhY3RpZCI6ICJzcHJpbmctd2ViIn0sIHsidmVyc2lvbiI6ICIxLjEuMyIsICJncm91cGlkIjogInNwcmluZ2ZyYW1ld29yayIsICJhcnRpZmFjdGlkIjogInNwcmluZy13ZWJtdmMifSwgeyJ2ZXJzaW9uIjogIjEuMS4zIiwgImdyb3VwaWQiOiAic3ByaW5nZnJhbWV3b3JrIiwgImFydGlmYWN0aWQiOiAic3ByaW5nLW1vY2sifSwgeyJ2ZXJzaW9uIjogIjIuMSIsICJncm91cGlkIjogImNvbW1vbnMtYXR0cmlidXRlcyIsICJhcnRpZmFjdGlkIjogImNvbW1vbnMtYXR0cmlidXRlcy1hcGkifSwgeyJ2ZXJzaW9uIjogIjIuMSIsICJncm91cGlkIjogImNvbW1vbnMtYXR0cmlidXRlcyIsICJhcnRpZmFjdGlkIjogImNvbW1vbnMtYXR0cmlidXRlcy1jb21waWxlciJ9LCB7InZlcnNpb24iOiAiMS4wLjQiLCAiZ3JvdXBpZCI6ICJ0YWdsaWJzIiwgImFydGlmYWN0aWQiOiAic3RhbmRhcmQifSwgeyJ2ZXJzaW9uIjogIjIuMC4xMSIsICJncm91cGlkIjogImNhcyIsICJhcnRpZmFjdGlkIjogImNhc2NsaWVudCJ9LCB7InZlcnNpb24iOiAiMS4yIiwgImdyb3VwaWQiOiAiYXNwZWN0aiIsICJhcnRpZmFjdGlkIjogImFzcGVjdGpydCJ9XQ"
    val mavenEntries = MavenEntry.readBase64EncodedJSONtoListOfMavenEntries(base64EncodedJson)
    mavenEntries should not be empty
  }
  "Reading a Base64 encoded JSON string of an empty array" should "result in an empty list" in {
    val base64EncodedJson = "W10="
    val mavenEntries = MavenEntry.readBase64EncodedJSONtoListOfMavenEntries(base64EncodedJson)
    mavenEntries should be(empty)
  }
  "A row from the dataset" should "describe a MavenEntry and a list of dependencies (List[MavenEntry])" in {
    val data = sqlContext.tsvFile(this.getClass.getResource("/singleLine.csv").getPath, useHeader = false).cache()
    MavenEntry.getFirstMavenEntryFromRow(data.first()) should not be null
    MavenEntry.getDependenciesFromRow(data.first()) should not be empty
  }
}
